### ISSUE TITLE
java.lang.NoClassDefFoundError error in support library 26.0.0 and above

### ISSUE THREAD

**Issue by neelayak** [Yalantis/Multi-Selection#3]
So I am using this library for a while but as u upgraded the lib things getting bad as i am getting error while using the library so plz fix this sir
` java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                               at com.yalantis.multiselection.lib.MultiSelectItemAnimator.resetAnimation(MultiSelectItemAnimator.kt:457)
                                                                               at com.yalantis.multiselection.lib.MultiSelectItemAnimator.animateMove(MultiSelectItemAnimator.kt:205)
                                                                               at android.support.v7.widget.SimpleItemAnimator.animatePersistence(SimpleItemAnimator.java:140)
                                                                               at android.support.v7.widget.RecyclerView$4.processPersistent(RecyclerView.java:551)
                                                                               at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:239)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3789)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3447)
                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1166)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:851)
                                                                               at android.support.design.widget.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:63)
                                                                               at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:136)
                                                                               at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                               at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:869)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16653)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                           	at android.`

**Comment by sadaks-me** [comment]
I'm facing the same issue, looking forward for a fix to this issue ASAP. Thank You.

**Comment by solusoftek** [comment]
i guess this library its no more manteined so i make this modifications for the error above, works fine now, firts clone the repo, integrate on your project and change the MultiSelectItemAnimator class with this code https://gist.github.com/solusoftek/b9e672c8ff5120452f64fa87deae4cda hope its help, great library by the way,

**Comment by neelayak** [comment]
Thx sir for the reply I will add this in my app which I am going to publish
